package pki

import (
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"fmt"
)

// MeshServerTLSConfig returns a TLS config for the gRPC HiveMesh server.
// Enforces mTLS: requires and verifies client certificates against the cluster CA.
// Uses dynamic cert loading so certs generated by InitCluster take effect without restart.
func MeshServerTLSConfig(dataDir string) (*tls.Config, error) {
	// Verify certs exist at config creation time
	if _, err := LoadNodeCert(dataDir); err != nil {
		return nil, fmt.Errorf("load node cert: %w", err)
	}
	if _, err := LoadCACert(dataDir); err != nil {
		return nil, fmt.Errorf("load CA cert: %w", err)
	}

	return &tls.Config{
		// Dynamic cert loading — re-reads from disk on each handshake.
		// This allows certs generated by InitCluster to take effect without restart.
		GetCertificate: func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
			cert, err := LoadNodeCert(dataDir)
			if err != nil {
				return nil, err
			}
			return &cert, nil
		},
		GetConfigForClient: func(*tls.ClientHelloInfo) (*tls.Config, error) {
			caCert, err := LoadCACert(dataDir)
			if err != nil {
				return nil, err
			}
			caPool := x509.NewCertPool()
			caPool.AddCert(caCert)
			return &tls.Config{
				GetCertificate: func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
					cert, err := LoadNodeCert(dataDir)
					if err != nil {
						return nil, err
					}
					return &cert, nil
				},
				ClientAuth: tls.RequireAndVerifyClientCert,
				ClientCAs:  caPool,
				MinVersion: tls.VersionTLS13,
			}, nil
		},
		ClientAuth: tls.RequireAndVerifyClientCert,
		MinVersion: tls.VersionTLS13,
	}, nil
}

// MeshClientTLSConfig returns a TLS config for outbound gRPC HiveMesh connections.
// Presents the node certificate as a client cert and verifies the server against the CA.
// Uses dynamic cert loading so certs generated by InitCluster take effect without restart.
func MeshClientTLSConfig(dataDir string) (*tls.Config, error) {
	if _, err := LoadNodeCert(dataDir); err != nil {
		return nil, fmt.Errorf("load node cert: %w", err)
	}
	if _, err := LoadCACert(dataDir); err != nil {
		return nil, fmt.Errorf("load CA cert: %w", err)
	}

	return &tls.Config{
		GetClientCertificate: func(*tls.CertificateRequestInfo) (*tls.Certificate, error) {
			cert, err := LoadNodeCert(dataDir)
			if err != nil {
				return nil, err
			}
			return &cert, nil
		},
		RootCAs:    loadCACertPool(dataDir),
		MinVersion: tls.VersionTLS13,
	}, nil
}

// loadCACertPool loads the CA cert pool from disk.
func loadCACertPool(dataDir string) *x509.CertPool {
	caCert, err := LoadCACert(dataDir)
	if err != nil {
		return nil
	}
	pool := x509.NewCertPool()
	pool.AddCert(caCert)
	return pool
}

// APIServerTLSConfig returns a TLS config for the gRPC HiveAPI server.
// Server-only TLS — does not require client certificates.
func APIServerTLSConfig(dataDir string) (*tls.Config, error) {
	nodeCert, err := LoadNodeCert(dataDir)
	if err != nil {
		return nil, fmt.Errorf("load node cert: %w", err)
	}

	return &tls.Config{
		Certificates: []tls.Certificate{nodeCert},
		MinVersion:   tls.VersionTLS13,
	}, nil
}

// CACertFingerprint returns the SHA-256 fingerprint of a CA certificate as a colon-separated hex string.
func CACertFingerprint(caCert *x509.Certificate) string {
	hash := sha256.Sum256(caCert.Raw)
	fp := ""
	for i, b := range hash {
		if i > 0 {
			fp += ":"
		}
		fp += fmt.Sprintf("%02X", b)
	}
	return fp
}
